### ISSUE TITLE
Update for jessie

### ISSUE THREAD

**Issue by DarthKeizer** [AlbrechtL/RPi-QEMU-x86-wine#10]
Mind upting project to jessie 👍 ?

**Comment by ekrekeler** [comment]
I second this. What would be even better though is if you showed the steps for how you made the image. I downloaded, compiled, and got your QEMU fork working on jessie, along with a fresh 32-bit clone of jessie, but whenever I try to run the start script or chroot manually, it gives me an error saying that there is no such file or directory for /bin/su or /bin/bash or whatever I'm trying to execute, even though it's there. What did you do to get this working?

**Comment by DarthKeizer** [comment]
project is dead unfortunatly :-1:
