### ISSUE TITLE
How can I add a new app to wine－user？

### ISSUE THREAD

**Issue by trevery** [AlbrechtL/RPi-QEMU-x86-wine#4]
I have a app named dr.com to add in my Pi, But I don't know how to realize it?
Can you tell me?

**Comment by chenxuuu** [comment]
I find that....the file is in "/home/pi/chroot-wheezy-i386/home/wine-user"
反正整个 wine 就在 /home/pi/chroot-wheezy-i386/home/wine-user 这里了。。
打开这个文件夹之后按 ctrl+H 可以看到隐藏的 .wine
然后就没了
