### ISSUE TITLE
Raspberry Pi 3 Version?

### ISSUE THREAD

**Issue by FattusMannus** [AlbrechtL/RPi-QEMU-x86-wine#5]
Flashed this to my RPi 3 and it just hung before boot.

Any chance of a version for Rpi3 please?

**Comment by AlbrechtL** [comment]
The current image doesn't support the RPi 3 because the RPi 3 didn't exist at that time.
Unfortunately there are no plans to create a new image with RPi 3 support.

**Comment by KarypidisParis** [comment]
Hi, 

can this image boot on raspberry pi 1? Is there any alternative option to run x86 app (linux or win) on raspberry pi 1 arm processor?

**Comment by AlbrechtL** [comment]
I tested it only on a RPi 2. You can try it on a RPi 1 and tell us your result.

**Comment by KarypidisParis** [comment]
I tried it out on RPi1 and RP3, and it didn't work! Thanks anyway! :)

**Comment by L30Yu** [comment]
hey, anyone got a chance to make it work on RPi3 ?? Or, maybe just need change little on this img? as the link from archlinux is actually using rpi2 img (https://archlinuxarm.org/platforms/armv8/broadcom/raspberry-pi-3)

**Comment by johncurcio** [comment]
@KarypidisParis I've managed to boot the image on a RPi1 and I'm running notepad.exe with no problems. It's a little slow but it does work on RPi1.

**Comment by KarypidisParis** [comment]
@johncurcio you followed the same procedure as explained or you did something else?

**Comment by johncurcio** [comment]
@KarypidisParis After I followed the same procedure I could ssh into the Pi, but had no display with the HDMI. Then I had to change the `/boot/config.txt` file to force HDMI output. I just added `hdmi_force_hotplug=1` and  `hdmi_drive=2` to the file and now the HDMI works.

**Comment by zeroflag** [comment]
Hi,

Is this supposed to work on a pi zero? When I boot the image the green flash blinks 8-9 times and it doesn't seem to work.

**Comment by MichaelSoftware** [comment]
Due to the fact that the pi zero has less power than the other pi. It wouldn't run GREAT. But Raspbian should at least boot, so i suggest trying to flash the RPI rom from a computer that ISNT Windows. Try using OSX or Ubuntu and if you still have the problem then yea i dont think the RPI Zero has enough power to run it. Rn im running on the Pi 2 and its taking 128 mb of ram just running notepad in the background.

**Comment by AlbrechtL** [comment]
mikerr did a image incl the Raspberry Pi 3.
 * https://github.com/mikerr/RPi-QEMU-x86-wine
 * https://sourceforge.net/projects/pi-qemu-wine/
