### ISSUE TITLE
MT4 on RPI

### ISSUE THREAD

**Issue by bigbro1985** [AlbrechtL/RPi-QEMU-x86-wine#6]
Hi,

Did you do this [http://mt4onrpi.blogspot.qa/2015/10/running-mt4-on-raspberry-pi-2-as-server.html](http://mt4onrpi.blogspot.qa/2015/10/running-mt4-on-raspberry-pi-2-as-server.html)

I have been trying to replicate this but have been unable to.

Thanks,

**Comment by AlbrechtL** [comment]
Please write the author of this article.
He said: "Are you interested in a mini tutorial how to install it and run it like a server let me know."
