### ISSUE TITLE
What Kind of Keyboard is setup?

### ISSUE THREAD

**Issue by MichaelSoftware** [AlbrechtL/RPi-QEMU-x86-wine#7]
I am trying to use an American English Keyboard but the OS is setup to detect another type of keyboard., if you can tell me how to change the keyboard layout so it is American English that would be appreciated.

**Comment by MichaelSoftware** [comment]
Figured out it was a german keyboard. Sorry but when i went to RPI Config i still couldnt change it...

**Comment by mikerr** [comment]
Later reply!  but this will fix it:
   setxkbmap gb
